### ISSUE TITLE
Error: cannot find module './src/emitter'

### ISSUE THREAD

**Issue by saesrpgmta** [yariplus/nodebb-plugin-rainbows#10]
Currently getting this error on NodeBB v1.11.2 when trying to use this plugin:

```
2019-02-06T14:12:57.380Z [4999/23748] - error: Error: Cannot find module './src/emitter'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Module.require.main.require (/var/****/require-main.js:8:10)
    at NodeBB (/var/****/node_modules/nodebb-plugin-rainbows/library.js:4:39)
    at Object.<anonymous> (/var/****/node_modules/nodebb-plugin-rainbows/library.js:11:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by PatheticMustan** [comment]
Can confirm I'm getting the same error. It also prevents me from making any posts, because "config.rainbows.postsEnabled" is not enabled.

"config.rainbows" doesn't even exist, so maybe there's a problem with starting it up? (Did the new update break it?)

I'm also running in 1.11.2

**Comment by saesrpgmta** [comment]
Any news on this?

**Comment by movegoo** [comment]
Same problem after update to V.1.12 :/

**Comment by PatheticMustan** [comment]
I guess we can just disable the plugin until it gets fixed. :(

**Comment by yariplus** [comment]
Should be fixed now. Apologies for the delay.

**Comment by saesrpgmta** [comment]
> 
> 
> Should be fixed now. Apologies for the delay.

Cheers, all working!
